api_platform:
  mapping:
    paths:
      - "%kernel.project_dir%/config/api_platform/resources"
  patch_formats:
    json: ["application/merge-patch+json"]
  swagger:
    api_keys:
      apiKey:
        name: Authorization
        type: header
  title: Symfony API Platform
  version: 1.0
  show_webby: false
